config:
  MD013:
    line_length: 400
    code_blocks: false
    tables: false
  MD025: false
  MD033: false
  MD041: false
  MD046: false
  MD014: false
  MD060: false
  MD036: false
  MD059: false
  MD045: false
  MD007:
    indent: 4
  MD032: false
  MD022: false
  MD031: false
  MD040: false
  MD047: false
ignores:
  - "**/node_modules"
