// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: query.sql

package db

import (
	"context"
)

const getHash = `-- name: GetHash :one
SELECT hash FROM urls
WHERE url = ? LIMIT 1
`

func (q *Queries) GetHash(ctx context.Context, url string) (string, error) {
	row := q.db.QueryRowContext(ctx, getHash, url)
	var hash string
	err := row.Scan(&hash)
	return hash, err
}

const insertHash = `-- name: InsertHash :exec
INSERT OR REPLACE INTO urls (
  url, hash
) VALUES (
  ?, ?
)
`

type InsertHashParams struct {
	Url  string
	Hash string
}

func (q *Queries) InsertHash(ctx context.Context, arg InsertHashParams) error {
	_, err := q.db.ExecContext(ctx, insertHash, arg.Url, arg.Hash)
	return err
}
