// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package db

import (
	"context"
)

type Querier interface {
	GetEntry(ctx context.Context, url string) (GetEntryRow, error)
	InsertHash(ctx context.Context, arg InsertHashParams) error
}

var _ Querier = (*Queries)(nil)
